### PR TITLE
Amitp

### LINKED ISSUE #81: Adding timeline in the achievements page
**Is your feature request related to a problem? Please describe.**
In the achievements page it has very simple ui and also there is no mention of date and time of the achievements 

**Describe the solution you'd like**
Instead of showing simply videos we can make a timeline of those video and show according to their timeline
image
we can do like the above image it would more attractive after doing this
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by amitp138**
## What is the change?
changed the ui of the achievements page and also adde link to the home page 

## Related issue?
closes: #81

## How was it tested?
I have also made it responsive and checked also tested with lighthouse
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines](https://github.com/BugBustersCommunity/website#how-to-contribute) while contributing.
-  [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-  [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html, css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by Aditi-Singh16** [comment]
image
The navbar on achievements page should just have the logo(left aligned just how its in ss) and the Achievements title (center aligned)
Completely change the navbar on achievements page, to something like this on clicking the logo we will be navigated back to homepage

**Comment by amitp138** [comment]
Ohk got it

**Comment by amitp138** [comment]
now the navbar looks like this 
Screenshot (600)
is it good or any other changes

**Review by Aditi-Singh16 — APPROVED** [review]

**Comment by Aditi-Singh16** [comment]
resolve conflicts and we can merge it

**Comment by amitp138** [comment]
Ohk Sure thx

**Comment by amitp138** [comment]
hello maam in this i am not getting the conflicts can you help me in this since i am doing this first please

**Comment by amitp138** [comment]
i think that somebody has changed the achievements page header and it is conflicting with my css

**Comment by amitp138** [comment]
done with the conflicts

**Comment by amitp138** [comment]
can you merge this now

**Comment by Aditi-Singh16** [comment]
Grt work!

**Comment by amitp138** [comment]
Thank you very much ma'am

**Comment by amitp138** [comment]
It was wonderful experience since it was my first open source contribution

**Comment by amitp138** [comment]
Hello ma'am can you please add the hactoberfest tag for the issue because this contribution will be counted for the hactoberfest please

**Comment by amitp138** [comment]
Thank you so much @siddhi-244  🙏🙏

**Pull request merged**
