### PR TITLE
changed the ui of social media links

### LINKED ISSUE #114: edit the social media links  ui
**Is your feature request related to a problem? Please describe.**
the links of the social media  of the website can be made more good looking by  changing the ui of it , I would love to work upon this . since it the about the social media links it should look more attractive and eyecachy
image
above links will look like below image
immm2
neim

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by amitp138**
## What is the change?
changed the ui of the footer social media links
now it looks like below
image

## Related issue?
closes: #114

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines](https://github.com/BugBustersCommunity/website#how-to-contribute) while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html, css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest 2022 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
For Twitter and Facebook icon, when it's expanded it shows the icon but for Instagram and snap chat it's not showing.  Try to add relevant icons such as LinkedIn instead of snapchat and link all the icons to the social media profiles

**Comment by amitp138** [comment]
Ohk will do it

**Comment by amitp138** [comment]
now is it ok?

**Comment by siddhi-244** [comment]
Discord spelling is wrong. Then we don't need Facebook and twitter

**Comment by amitp138** [comment]
Ohk got it any other social media to add ?

**Comment by siddhi-244** [comment]
> Ohk got it any other social media to add ?

No

**Comment by amitp138** [comment]
is it fine now ?

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Link the icons to our socials

**Comment by amitp138** [comment]
can you give the official  links of it ?

**Comment by siddhi-244** [comment]
I think you can figure it out. Discord link is given below 
https://discord.gg/5AzjNtV8vG

**Comment by amitp138** [comment]
yeah got the links it took some time but atlast found all

**Comment by amitp138** [comment]
now all good ?

**Review by siddhi-244 — APPROVED** [review]
Lgtm

**Comment by amitp138** [comment]
Thank you so much @siddhi-244

**Pull request merged**
