### PR TITLE
I have added some amazing Animation. Please check it out.

### PR DESCRIPTION
**Pull request by alisamadiii**
## What is the change?
Added Animation 

## Related issue?
#66 

## How was it tested?
I tested it and it was amazing

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [ ] I'm HSOC22 contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by siddhi-244** [comment]
Please resolve conflicts !

**Comment by alisamadiii** [comment]
Ok, I am doing it RN

**Comment by alisamadiii** [comment]
Sorry, it destroyed the layout. IDK

**Comment by alisamadiii** [comment]
I'll fix it.

**Comment by alisamadiii** [comment]
Is it working fine right now?
@siddhi-244

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
