### PR TITLE
Added social media links

### LINKED ISSUE #21: Add photos in cards and social media links
- Will add photos of the members in the cards
- will add social media links (twitter, insta, github, linkedin) of the members in the cards

### PR DESCRIPTION
**Pull request by tanya-gupta25**
## What is the change?
--Added all social links(twitter,insta,github,linkedin) of Siddhi, Aditi & Girija
-- Added only Linkedin id's of rest of members
-- Couldn't add pictures because don't have them

## Related issue?
closes: #21

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by siddhi-244** [comment]
My linkedin link is not working. Also there are no pictures. I told you to take it from linkedin

**Comment by tanya-gupta25** [comment]
> My linkedin link is not working. Also there are no pictures. I told you to take it from linkedin

Ohh I'll see the link, but about images I informed you earlier that they are not downloadable from LinkedIn that's why I asked for the folder earlier

**Comment by tanya-gupta25** [comment]
> My linkedin link is not working. Also there are no pictures. I told you to take it from linkedin

@siddhi-244  I checked your linkedin Link , it's working absolutely fine at my end , I have checked it in deploy preview its working

**Comment by siddhi-244** [comment]
When I checked it showed error. Lemme see

**Review by siddhi-244 — APPROVED** [review]
Lgtm

**Pull request merged**
