### PR TITLE
Navbar 

### PR DESCRIPTION
**Pull request by SumitKanth**
- Completed the assigned work.

### CODE REVIEW

**Comment by siddhi-244** [comment]
The navbar is showing unexpected behavior on mobile view

**Comment by SumitKanth** [comment]
> The navbar is showing unexpected behavior on mobile view

doing code

**Comment by SumitKanth** [comment]
Did some changes plz check.

**Comment by siddhi-244** [comment]
Nope again it's showing unexpected behavior!

**Comment by SumitKanth** [comment]
Can you share a screen sort, I am not getting it

**Comment by siddhi-244** [comment]
You can see it in deployed link

**Comment by SumitKanth** [comment]
will do changes

**Comment by SumitKanth** [comment]
Done with navbar issue

**Comment by siddhi-244** [comment]
> Done with navbar issue

Can you share a screenshot

**Comment by SumitKanth** [comment]
Screenshot (274)
Screenshot (275)

**Comment by SumitKanth** [comment]
@siddhi-244 didi

**Comment by siddhi-244** [comment]
> Screenshot (274) Screenshot (275)

On desktop mode as well

**Comment by SumitKanth** [comment]
Screenshot (276)

**Comment by siddhi-244** [comment]
> Screenshot (276)

Awesome.

**Review by siddhi-244 — APPROVED** [review]
LGTM. Keep the spirit up🥳🥳🥳

**Comment by SumitKanth** [comment]
thanks 👀

**Pull request merged**
