### PR TITLE
Fix grammar and Remove lorem ipsum

### PR DESCRIPTION
**Pull request by ashmeet-ashmeet**
Resolves issue #6

### CODE REVIEW

**Comment by ashmeet-ashmeet** [comment]
Just a heads up, I'm sorry if you see too many changes in the file. It's just, I had a formatter switched on in my vscode and it fixed the indendation everywhere and I didn't notice until i had already made all my changes.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by siddhi-244** [comment]
Let's wait for @Aditi-Singh16 . Please do review it !

**Comment by Aditi-Singh16** [comment]
> Just a heads up, I'm sorry if you see too many changes in the file. It's just, I had a formatter switched on in my vscode and it fixed the indendation everywhere and I didn't notice until i had already made all my changes.

Hi, please remove the formatter changes

**Comment by ashmeet-ashmeet** [comment]
done!

**Review by Aditi-Singh16 — APPROVED** [review]

**Comment by Aditi-Singh16** [comment]
> done!

Thanks! merged :D

**Pull request merged**
