### PR TITLE
navbar width fixed

### LINKED ISSUE #68: Navbar width is too large. Overflowing the client width screen
**Describe the bug**
Navabar width is large.

## screenshots

https://user-images.githubusercontent.com/107163858/193433784-db2e4bc8-439b-48f3-abde-384b211eac89.mp4

**Additional context**

### PR DESCRIPTION
**Pull request by sanyamjain04**
## What is the change?
navbar width unit has changed from vw to % 

## Related issue?
closes: #68  navbar width fixed

## How was it tested?
I changed the width from 100vw to 100%. Now it is working fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.

### CODE REVIEW

**Comment by siddhi-244** [comment]
> ## What is the change?
> navbar width unit has changed from vw to %
> 
> ## Related issue?
> closes: #68 navbar width fixed
> 
> ## How was it tested?
> I changed the width from 100vw to 100%. Now it is working fine.
> 
> ## Checklist:
> Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:
> 
> * [x]  I have followed the Contribution Guidelines while contributing.
> * [x]  I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  I have tested the code before submission.
> * [x]  I have formatted the code . (You can use any html,css beautifier)
> * [x]  My changes generates no new warnings.

Solve this for mobile view too !

**Comment by Aditi-Singh16** [comment]
@sanyamjain04  any updates?

**Comment by sanyamjain04** [comment]
> @sanyamjain04 any updates?

I have made changes in nvbar

**Comment by sanyamjain04** [comment]
> @sanyamjain04 any updates?

I think someone else has already changed the width of navbar. so I am closing this PR.

**Pull request closed without merging**
