### PR TITLE
Footer 

### PR DESCRIPTION
**Pull request by SumitKanth**
Modified footer

### CODE REVIEW

**Comment by siddhi-244** [comment]
Follow the pr template!

**Comment by SumitKanth** [comment]
What to do ?

**Comment by SumitKanth** [comment]
## What is the change?
- changed design of footer from scratch.
- Made footer responsive.

## Related issue ?
#37 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes ```[x]```:

- [ ] I have followed the [Contribution Guidelines](https://github.com/BugBustersCommunity/website/pull/41) while contributing.
- [ ]  I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the - [ same update/change.
- [ ]  I have made corresponding changes to the documentation.
 - [ ] I have tested the code before submission.
 - [ ] I have formatted the code . (You can use any html, css beautifier)
 - [ ] My changes generates no new warnings.
 - [ ] -I'm HSOC22 contributor.
 - [ ] I have commented my code, particularly in hard-to-understand areas.

**Comment by siddhi-244** [comment]
There are conflicting files. Add a screenshot of your change

**Comment by SumitKanth** [comment]
Web page or file  screen sort ? @siddhi-244

**Comment by siddhi-244** [comment]
> Web page or file screen sort ? @siddhi-244

The changes you made ?

**Comment by SumitKanth** [comment]
Screenshot (305)
Screenshot (306)

**Comment by siddhi-244** [comment]
Resolve merge conflicts, then I will merge ur pr

**Comment by SumitKanth** [comment]
@siddhi-244 I can't understand what is the conflicts

**Comment by Aditi-Singh16** [comment]
> @siddhi-244 I can't understand what is the conflicts

you need to resolve these
image

**Comment by SumitKanth** [comment]
@siddhi-244 @Aditi-Singh16 now ?

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by SumitKanth** [comment]
@siddhi-244 made navbar from scratch and got level-1 👀

**Comment by siddhi-244** [comment]
Will give level 2. But make sure you always respect other person's decisions too. The footer was made by someone already !

**Comment by SumitKanth** [comment]
@siddhi-244 sorry, typo mistake I was saying that edited navbar from scratch.

**Pull request merged**
