### PR TITLE
Improved social icons

### LINKED ISSUE #13: Improve the social media icons in the cards
**Describe the bug**
Social media icons in the cards needs to be improved. I'll be adding better icons here instead of them

### PR DESCRIPTION
**Pull request by tanya-gupta25**
## What is the change?

1. Improved social icons 
2.  changed linkedin icon & replaced google, youtube with instagram & github
3. Added hover effect on the icons

## Related issue?
closes: #13 

## GIF/video of the working of component you created:
image

### CODE REVIEW

**Comment by siddhi-244** [comment]
Instead of Facebook,  can you add Twitter icon ?

**Comment by tanya-gupta25** [comment]
Okay will do it

**Comment by tanya-gupta25** [comment]
image

**Review by siddhi-244 — APPROVED** [review]
LGTM🥳🥳

**Review by Aditi-Singh16 — APPROVED** [review]

**Pull request merged**
