### PR TITLE
Fix issue #18 Added a contact section

### LINKED ISSUE #18: Want to add a contact section
**Is your feature request related to a problem? Please describe.** 

There is no proper and direct communication channel between site owner and user
**Describe the solution you'd like**

A want to add a good contact page with great css styles which will really helpful to user.

### PR DESCRIPTION
**Pull request by vedsom**
Added a contact page

## What is the change?
Now there is a separate Contact Page

## Related issue?
closes: #18

## How was it tested?
Go to contact section and observe the changes
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

https://user-images.githubusercontent.com/96954912/180668433-052db7d2-e976-4f8e-bcd3-5f483ec538d6.mp4

Contact Page - Google Chrome 25-07-2022 04_00_59

### CODE REVIEW

**Comment by vedsom** [comment]
@siddhi-244 here's the work is done, hope you liked it. Kindly review the PR and also add the tag of level. Thankyou!!

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by vedsom** [comment]
@Aditi-Singh16 kindly review the PR?

**Comment by siddhi-244** [comment]
Please resolve conflicts

**Comment by vedsom** [comment]
> Please resolve conflicts

@siddhi-244  Solved

**Pull request merged**
