### PR TITLE
Added achievement section and footer improved

### LINKED ISSUE #42: Achievements tab in navbar
**Describe the solution you'd like**
Add all achievements, webinars and workshops conducted by bugbusters till now
take reference from here -  [BugBusters YT](https://www.youtube.com/channel/UCqH6JeCTHngoGjV-5VlKNHg)

### PR DESCRIPTION
**Pull request by vedsom**
## What is the change?
added achievement section and improved footer

## Related issue?
closes: #42 and #38 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by vedsom** [comment]
@siddhi-244  sorry for being 17 min late. I have added achievement section and improved footer solve issue #42 and #38 simultaneously. kindly review PR.

**Comment by siddhi-244** [comment]
There are 2 input bars in footer for the newsletter thing. Remove one

**Comment by vedsom** [comment]
> There are 2 input bars in footer for the newsletter thing. Remove one

@siddhi-244 done!!! Review it.

**Comment by vedsom** [comment]
@siddhi-244 any updates!!

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove the json file and I will merge it

**Comment by vedsom** [comment]
> Remove the json file and I will merge it

@siddhi-244  I have removed the json file. Kindly review it.

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
