### PR TITLE
Footer redesign

### LINKED ISSUE #16: Improve footer of the website in mobile view!
**Is your feature request related to a problem? Please describe.**
Improve footer of the website in mobile view!

### PR DESCRIPTION
**Pull request by vikas-kmr1**
## What is the change?
Improved design of  footer in mobile view

## Related issue?
closes: #16 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Change the footer icons too. Add linkedin, Instagram and website icons !

**Comment by siddhi-244** [comment]
Why so many commits? Aren't you using git? Don't do it using uploads

**Comment by siddhi-244** [comment]
LinkedIn? Can you stick to the theme of website. Just like previous icons. Please don't make so many commits. Use git !

**Comment by vikas-kmr1** [comment]
@

> LinkedIn? Can you stick to the theme of website. Just like previous icons. Please don't make so many commits. Use git !

Keep remembering for the next time .

**Pull request closed without merging**
