### PR TITLE
enhancing navbar, added dark-mode, improved the css

### PR DESCRIPTION
**Pull request by THE-AryanKumar**
## What is the change?
enhanced navbar , added dark-mode toggle , improved the CSS , aligned the footer. fixed the navbar issues and icons styling.

## Related issue?
closes: #65 responsiveness

## How was it tested?
Pretty Standard 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [X] I have followed the [Contribution Guidelines]() while contributing.
-   [X] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [X] I have made corresponding changes to the documentation.
-   [X] I have tested the code before submission.
-   [X] I have formatted the code . (You can use any html,css beautifier)
-   [X] My changes generates no new warnings.
-   [X] I'm HSOC22 contributor.
-   [X] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by THE-AryanKumar** [comment]
Please review the changes and approve the request. Thank You

**Comment by Aditi-Singh16** [comment]
Navbar looks good, but remove the dark mode we don't need it
then we can merge it

**Comment by THE-AryanKumar** [comment]
@Aditi-Singh16  I have removed the dark-mode. Pls review and approve...!
Can you label it too "Hacktoberfest2022".

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Look at the logo in mobile view! It's in between align it properly

**Comment by siddhi-244** [comment]
This issue is already resolved !

**Comment by siddhi-244** [comment]
Link the issue which you are solving ?

**Comment by THE-AryanKumar** [comment]
@siddhi-244 Improving the Navbar. I have added bracket animation effect.
Check it out on Screenshot.

**Pull request closed without merging**
