### PR TITLE
Changed Achivements page 

### LINKED ISSUE #81: Adding timeline in the achievements page
**Is your feature request related to a problem? Please describe.**
In the achievements page it has very simple ui and also there is no mention of date and time of the achievements 

**Describe the solution you'd like**
Instead of showing simply videos we can make a timeline of those video and show according to their timeline
image
we can do like the above image it would more attractive after doing this
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by amitp138**
## What is the change?
changed the layout of the videos and headings

## Related issue?
closes: #81

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-  [x] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by Aditi-Singh16** [comment]
Looks good, but add a navigation button back to homepage

**Comment by amitp138** [comment]
Ohk

**Comment by amitp138** [comment]
Will do it by today

**Comment by amitp138** [comment]
added the neccesary  changes and made a new pr kindly check it and provide your feedback

**Pull request closed without merging**
