### PR TITLE
Update contact.html

### LINKED ISSUE #33: Improving the contact us page
**Is your feature request related to a problem? Please describe.**
Improving the contact us page

**Describe the solution you'd like**
The contents of the page will be a little bit more aligned and some changes in its design

### PR DESCRIPTION
**Pull request by deepshikha2708**
## What is the change?
Changed the backgroud colour and the submit button but couldn't bring them in the center.

## Related issue?
closes: #33 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Contribution Guidelines]() while contributing.
-   [ ] I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
-   [ ] I have made corresponding changes to the documentation.
-   [x] I have tested the code before submission.
-   [x] I have formatted the code . (You can use any html,css beautifier)
-   [ ] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by siddhi-244** [comment]
> ## What is the change?
> Changed the backgroud colour and the submit button but couldn't bring them in the center.
> 
> ## Related issue?
> closes: #33
> 
> ## How was it tested?
> Remove this line and tell us how the code was tested.
> 
> ## Checklist:
> Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:
> 
> * [ ]  I have followed the Contribution Guidelines while contributing.
> * [ ]  I have checked there aren't other open [Pull Requests](https://github.com/BugBustersCommunity/website/pulls) for the same update/change.
> * [ ]  I have made corresponding changes to the documentation.
> * [ ]  I have tested the code before submission.
> * [ ]  I have formatted the code . (You can use any html,css beautifier)
> * [ ]  My changes generates no new warnings.
> * [ ]  I'm HSOC22 contributor.
> * [ ]  I have commented my code, particularly in hard-to-understand areas.
> 
> ## GIF/video of the working of component you created:
> Add here the GIF you created.

Fill the details properly. Check the boxes if you have fulfilled the tasks

**Comment by deepshikha2708** [comment]
what do I need to do in this @siddhi-244 ?

**Comment by siddhi-244** [comment]
Check the boxes , which describes the tasks done by you !

**Comment by deepshikha2708** [comment]
okay I did @siddhi-244

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can you keep the theme same as the main page?

**Review by Aditi-Singh16 — APPROVED** [review]

**Comment by deepshikha2708** [comment]
I did the changes...only changed the submit button but couldnt bring it to center.

**Comment by siddhi-244** [comment]
> I did the changes...only changed the submit button but couldnt bring it to center.

Change the colour of submit button

**Comment by deepshikha2708** [comment]
what colour?

**Comment by deepshikha2708** [comment]
green?

**Comment by siddhi-244** [comment]
Light blue works

**Comment by deepshikha2708** [comment]
done

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
